### ISSUE TITLE
Missing anyref subtyping changes

### ISSUE THREAD

**Issue by RReverser** [AssemblyScript/wabt.js#16]
I'm not 100% sure yet where the issue lies, but https://github.com/WebAssembly/wabt/commit/bf46c08b05fc6fcc457f1657e936fab24b4dceee has implemented spec changes to the `ref.null` and `ref.is_null` that now require a type parameter.

That commit was merged on 28 May, so in theory I'd expect those changes to be included in the latest nightly which is `20200603`.

However, snippets like following fail parsing even with `reference_types` feature enabled:

```wat
(module
  (func
    (ref.null func) ;; <-- temp.wat:7:15: error: unexpected token func, expected ).
    drop
  )
)
```

cc @dcodeIO @binji

**Comment by binji** [comment]
I think it may be that we don't have a recent wabt release, which was complicated by the fact that we switched over to GitHub actions completely. I'll take a look.

**Comment by RReverser** [comment]
Yeah but wabt.js builds nightlies independently (at least in theory) and it did so on 3rd of June as seen above, but for some reason doesn't include this change from 28th of May.

**Comment by RReverser** [comment]
Ping. Any news here on either side? This is concerning because it means wasm-feature-detect currently tests for outdated syntax / binary.

**Comment by binji** [comment]
I'm wondering if it builds "nightly" but uses the libwabt.js directly from the wabt repo. If so, that might explain it, since that is likely out-of-date. I'm attempting to update it now, but having some issues.

**Comment by dcodeIO** [comment]
I believe what happened here is that the bot has been using fastcomp to compile (upstream didn't work up to not long ago), but the main repo meanwhile updated the build to work with upstream, with fastcomp failing now. Related: https://github.com/AssemblyScript/wabt.js/pull/15

**Comment by dcodeIO** [comment]
Looked into this a little more, and I think I've identified the remaining problems. First of all that it doesn't compile with fastcomp anymore, but that's rather a good thing because upstream now works. Secondly, there has been a change to `MODULARIZE_INSTANCE` in Emscripten (in fact, it has been removed and WABT now uses the new `MODULARIZE`), so the API changed from

```ts
// previous
const wabt = require("wabt")();
...
```

to

```ts
// current
require("wabt")().then(wabt => {
  ...
});
```

Now looking into including the command line tools that the upstream build script now compiles to JS as well, as part of the package

* wasm2c
* wasm2wat
* wast2json
* wat2wasm
* wasm-decompile
* wasm-interp
* wasm-objdump
* wasm-opcodecnt
* wasm-strip
* wasm-validate
* wat-desugar

If there's an important tool missing, or if one of these doesn't make a lot of sense to ship with the package, let me know. Progress so far is in https://github.com/AssemblyScript/wabt.js/pull/15

**Comment by dcodeIO** [comment]
Merged the PR now. An up-to-date build should become available on npm with the next successful scheduled build (at 0 UTC).

**Comment by dcodeIO** [comment]
Should be on npm now, v1.0.17.
